#SPDX-License-Identifier: MIT-0
---
# tasks file for webserver
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Create Hello World index.html
  copy:
    src: templates/index.html
    dest: /var/www/html/index.html

- name: Ensure nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: true
  notify: Restart the Nginx service
