name: Ansible Playbook CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook nginx_hello.yml -i hosts.ini
